### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by matthewdippel** [matthewdippel/quickalias#1]
- [x] Rewrite file i/o to use BufRead/BufWrite for testability
- [x] Add file i/o tests
- [x] Add installation instructions / script

**Comment by matthewdippel** [comment]
Installing script finished by commit b0fa7fc397955de543695c30bde6ad195f1a4d8a

**Comment by matthewdippel** [comment]
Refactored to use unit testable read / write methods in commits ae7a5d94b9b1d0589b17e4421090a988765d6c98 and bf5115230300459f6f3e3738484f60d83b83921a

**Comment by matthewdippel** [comment]
File read/write integration testing added by ffeac7cf3cd895d459513c63dbf61c54954b940a and 0f6e814f172e47892efe25191e858018239f7edc
